### ISSUE TITLE
aggregate all fields to be marked as required and toast

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#671] opened 2024-03-25 07:15 UTC
Blank save- Needs toast with notification, all fields to be marked as required

**Comment by fatchat** [comment] 2024-03-25 14:50
no longer allows user to proceed without complete form
BUT
no indications e.g. toast / cell highlighting / helpful text etc

**Comment by fatchat** [comment] 2024-03-29 02:03
#735

**Comment by Ishankoradia** [comment] 2024-04-01 10:00
duplicate of #735

**Comment by fatchat** [comment] 2024-04-16 03:49
![Image](https://github.com/DalgoT4D/webapp/assets/2160416/305d734e-d74e-4693-b15b-b176fd803e82)

**Closed by fatchat** 2024-04-16 03:49 UTC
Labels: UI transform- medium
