### ISSUE TITLE
Group By issue/bug- save form incomplete

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#681] opened 2024-03-25 08:07 UTC
Group by	Leave some fields empty and try to save	
For output column name empty it takes me back to the cell to fill, for other empty cells save simple doesnt work.
Form response needs to be consistent - 
--take me to the relevant/first unfilled cell
-- have asterisks on all required fields
-- toast popup if form is not filled fully 

https://jam.dev/c/e60e515b-5b95-445c-afaa-eb483d3b30fb

**Comment by nairabhishek73** [comment] 2024-03-28 13:16
--take me to the relevant/first unfilled cell- Not done (don't need to do right away)
-- have asterisks on all required fields-Done
-- toast popup if form is not filled fully- Not done (need to do)

**Comment by fatchat** [comment] 2024-03-29 05:53
#735

**Comment by Ishankoradia** [comment] 2024-04-01 09:59
@nairabhishek73 we will do form validation and show errors below the input instead of showing toast errors. 

backend api errors will be shown through toast when you hit save.

**Comment by Ishankoradia** [comment] 2024-04-01 09:59
duplicate of #735

**Comment by mdshamoon** [comment] 2024-04-16 08:03
Fixed by #749

**Closed by mdshamoon** 2024-04-16 08:03 UTC
Labels: UI transform- medium
