### ISSUE TITLE
Delay between clicking sync on connection and the button switching. In the meantime i'm still able to click.

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1021] opened 2024-07-18 11:42 UTC
NA

**Comment by fatchat** [comment] 2024-07-18 13:16
duplicate of https://github.com/DalgoT4D/webapp/issues/1005 
@himanshudube97 has your fix been released?

**Comment by himanshudube97** [comment] 2024-07-18 20:16
Yes. It's released.

**Comment by fatchat** [comment] 2024-07-19 02:20
oh i see what happened.. the PR was merged but we didn't release to production. i've done it now

**Closed by fatchat** 2024-07-19 02:20 UTC
