### ISSUE TITLE
Drop form bugs

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#661] opened 2024-03-25 06:41 UTC
1) Drop one column- Name of first drop column populates in second input
- https://jam.dev/c/bae1ba67-823f-407e-a0dd-76c497ffa3ba
2) Delete a drop selection- Works. But the form is populating very oddly, the most recent entry is made at the bottom but populates at the top of the list	
- https://jam.dev/c/dd6b1d05-e23c-4118-9f12-838a0d9cb365

**Comment by fatchat** [comment] 2024-03-25 06:44
(1) is a duplicate of https://github.com/DalgoT4D/webapp/issues/602
(2) is a duplicate of https://github.com/DalgoT4D/webapp/issues/646#issuecomment-2016521052

**Closed by fatchat** 2024-03-25 06:44 UTC
Labels: UI transform- medium
