### ISSUE TITLE
Screen flashing when opening platform and when opening transform section

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#623] opened 2024-03-21 06:27 UTC
https://jam.dev/c/361e6014-7d8a-4595-891f-40858620fc7f

**Comment by fatchat** [comment] 2024-03-21 07:42
duplicate of #618

**Comment by nairabhishek73** [comment] 2024-03-22 07:01
Its still happening though.

https://jam.dev/c/3b30d007-960e-45f0-9778-0e0d7493ed2b

**Comment by fatchat** [comment] 2024-03-22 08:37
Yes yes it's a duplicate

**Closed** 2024-03-22 09:01 UTC
Labels: UI transform- medium
